name: Mamoru
favicon: null
layout_spectrum: 0.61777
typography_spectrum: 0.30112
title: we protect what you love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#433124'
    - '#907255'
    - '#f4f6f3'
    - '#96967f'
    - '#851c33'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
