name: Mamoru
favicon: null
layout_spectrum: 0.28163885697722435
typography_spectrum: 0.07591245695948601
title: we protect what you love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5043051897082478
  lightness: 0.6035895042587072
  saturation: 0.6259274003095925
  rhythmicContrast: 0.423008743673563
purpose: []
